AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 512
    Timeout: 30

Resources:
  layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: chrome-aws-lambda
        ContentUri: code/
        CompatibleRuntimes:
          - nodejs18.x
          - nodejs20.x

  node18:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole

  node20:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs20.x
      Policies:
        - AWSLambdaBasicExecutionRole
